### ISSUE TITLE
[Attention] {24-12-08} 브랜치 관련 최종 공지 (SourceTree / Github) (사진 첨부)

### ISSUE THREAD

**Issue by cookiecookiekim** [LYNK-LIFE/Groupware#81]
<작업 진행 방법 최종 공지>

1. 작업 시작 전, main 브랜치 pull 받기
  : 동기화 용도 
![1](https://github.com/user-attachments/assets/f0a29a45-8697-4d78-86a1-33e8bb3cfac4)

2. 각자 기능에 맞는 이름으로 브랜치 생성
  : ex) loginPageEJ (기능+ 이름 초성)
![2](https://github.com/user-attachments/assets/7e195129-6c77-4df0-bff3-d36c41d7848b)
![3](https://github.com/user-attachments/assets/73df8269-d5b8-408d-b215-9794b6fdfe4b)

3. 해당 브랜치로 작업 진행
  : dev, main 에서 작업하지 않도록 주의
![4](https://github.com/user-attachments/assets/5674df86-b0f2-4fb8-80a0-b690e3cafdca)

4. 본인 브랜치에 수정 사항 커밋 (PUSH 금지)
![5](https://github.com/user-attachments/assets/9d447acc-47f9-4643-88a2-8603d23d4cc3)
![6](https://github.com/user-attachments/assets/077139fc-0ed8-4fc7-9c79-27a9c35b2ec4)
![7](https://github.com/user-attachments/assets/9141c53a-1907-4885-80fe-34b17cdcd037)

5. 작업 완료 후, 본인이 dev(test용) 브랜치에 merge
  : sourceTree 내에서 merge
![8](https://github.com/user-attachments/assets/834eb7ec-6b07-46cb-81b2-0a7401d00af1)
![9](https://github.com/user-attachments/assets/1034c72c-c58b-4e70-bf0c-cc087ff56ac7)
![10](https://github.com/user-attachments/assets/4ec063cd-7bce-403a-96c4-15ec786f4a87)
![11](https://github.com/user-attachments/assets/22ec5de3-b206-4481-af11-3bdc6ad4b846)
![12](https://github.com/user-attachments/assets/9b9fe071-f451-40e3-ab65-1b3e9b37b04c)
![13](https://github.com/user-attachments/assets/22ab80a1-f38f-482d-a45c-62a4089283c0)

6. dev 브랜치에서 기능이 잘 돌아가는지 테스트 진행
  : ex) 한 page 단위 (기준 협의 필요)

7. 기능이 이상 없이 작동하면 '본인의 브랜치'를  '본인의 브랜치'로 push
  이후 pull-Request 작성
  : dev 또는 main 이 아닌 본인 브랜치로 올라가도록 유의
![14](https://github.com/user-attachments/assets/4780629e-2b90-4890-a6c5-35f0c08bae80)
![15](https://github.com/user-attachments/assets/3dea7564-b18f-4703-ab93-05f3406ef57d)
![16](https://github.com/user-attachments/assets/2887474e-ab38-4465-ae8a-0568d6c97f79)
![17](https://github.com/user-attachments/assets/541c3c00-f2d0-4385-b709-37cea86e66ca)

8. 형상 관리자는 merge 및 테스트 진행.

9. main에 merge 완료 후 본인의 브랜치 모두 '강제'삭제 (로컬 / 원격)
![18](https://github.com/user-attachments/assets/59a69e88-2b9a-47f0-a679-f6fcb35cba8a)
![19](https://github.com/user-attachments/assets/581a67ae-e315-4d16-a14d-06bd1f18b514)
![20](https://github.com/user-attachments/assets/c10931df-a351-4cea-bd94-b4b5fa78e6c6)
![21](https://github.com/user-attachments/assets/cae24baa-2388-4129-8c9e-958097702bc7)

10. 1~9 반복

**Comment by rraaccoon** [comment]
![image](https://github.com/user-attachments/assets/4acd5669-5416-475c-9a98-d2b1ff468478)
